Remove use of static fields in examples
domeengine/dome pull request #175
Opened 2021-02-20 13:12 UTC by BenStigsen

Fixes #174

2021-02-20 13:17 UTC, BenStigsen commented
All examples seem to work, I'm not able to test examples/plugin though, since I'm missing a `test.dll` file.

2021-02-22 08:49 UTC, avivbeeri requested changes
Small sentence change. There is also an example in the Plugin documentation which will need updating.

2021-02-22 08:49 UTC, avivbeeri commented on README.md
> +Your game's entry point must contain a `Game` class which contains at least `init()`, `update()` and `draw(_)` methods.
This should say "Your game's entry point must contain a `Game` variable, which holds an object with at least..."

2021-02-22 11:48 UTC, avivbeeri approved these changes

2021-02-22 11:48 UTC, merged